### ISSUE TITLE
[BUG] Linux --copyOnly issue is still present

### ISSUE THREAD

**Issue by eggsy** [Timeraa/DevScript#5]
This still happens on my Linux.

![image](https://user-images.githubusercontent.com/13917975/103832651-a531f180-5033-11eb-8cde-7fedecfe1c51.png)

**Comment by Timeraa** [comment]
Can you give me the node version you're using?

**Comment by eggsy** [comment]
> Can you give me the node version you're using?

Sure, here I have this old machine running for almost a year with an _not the latest_ version of Node, should I update?

![image](https://user-images.githubusercontent.com/13917975/104093293-8c495c00-523e-11eb-9a32-86e5229c1ae8.png)

**Comment by Timeraa** [comment]
Can you try it with the latest version (2.0.5)? I changed the compile target to ES5 as you use node <14 which doesn't support optional chaining

**Comment by eggsy** [comment]
Yep, now it works (without updating the Node version). Great!

![image](https://user-images.githubusercontent.com/13917975/104095701-38923f00-524d-11eb-82f1-19f423a739bc.png)
